# Site settings
title: Yohanes Nicolas Paulo Kwarrie
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yohanes Nicolas Paulo Kwarrie
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: polo.use.email@gmail.com
linkedin_username: yohanes-nicolas-paulo-kwarrie
github_username:  polapolo
instagram_username: polokuro
# twitter_username: lorem_ipsum
# facebook_username: mauricio.urraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
